In [1]:
number = [10,20,30,40,]
print(number)

[10, 20, 30, 40]


In [2]:
import numpy as np
numbers = np.array([5,10,15,20])
print(numbers)


[ 5 10 15 20]


In [3]:
number = [2,4,6,8]
print(number)

[2, 4, 6, 8]


In [4]:
import numpy as np
numbers = np.array([2,4,6,8])
print(numbers)


[2 4 6 8]


In [5]:
#CHALLENGING PROBLEM
import numpy as np
age = np.array([14,22,21,45,50])
print(age)
print(age * 2)
print(age + 5)

[14 22 21 45 50]
[ 28  44  42  90 100]
[19 27 26 50 55]


In [7]:
import numpy as np
number = np.array([100, 200, 300, 400])
print(number)

[100 200 300 400]


In [9]:
import numpy as np
number = np.array([
    [1,2],
    [3,4]
])

print(number)
    

[[1 2]
 [3 4]]


In [10]:
import numpy as np
ones = np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#CHALLENGING PROBLEM
import numpy as np
multiple = np.arange(5, 51, 5)
print(multiple)

[ 5 10 15 20 25 30 35 40 45 50]


In [17]:
#DIMENSION
import numpy as np
number = np.array([5, 10, 15, 20, 25])
print(number.shape)

(5,)


In [20]:
import numpy as np
number = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(number.shape)
    

(3, 2)


In [21]:
import numpy as np
zeros = np.zeros((4,5))
print(zeros.shape)


(4, 5)


In [22]:
#CHALLENGING PROBLEM
import numpy as np
ones = np.ones((5,4))
print(ones.shape)

num_rows = ones.shape[0]
num_cols = ones.shape[1]

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_cols}")

(5, 4)
Number of rows: 5
Number of columns: 4


In [23]:
import numpy as np
number = np.array([8, 16, 24, 32])
print(number)
print(number.ndim)

[ 8 16 24 32]
1


In [25]:
import numpy as np
matrix = np.array([
    [10, 20],
    [30, 40]
])

print(matrix)
print(matrix.ndim)


[[10 20]
 [30 40]]
2


In [27]:
import numpy as np
matrix = np.array([
     [
  [1, 2],
  [3, 4]
 ],
 [
  [5, 6],
  [7, 8]
 ]
])
print(matrix)
print(matrix.ndim)

    

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [28]:
#CHALLENGING PROBLEM
import numpy as np
matrix = np.zeros((2, 3, 4))
print(matrix)
print(matrix.shape)
print(matrix.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
3


In [30]:
#INDEXING
import numpy as np
number = np.array([5, 10, 15, 20, 25])
print(number[0])
print(number[4]) #we can use negative indexing as well

5
25


In [34]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(matrix[0,1])
print(matrix[1,0])
print(matrix[1,2])

    

2
4
6


In [35]:
import numpy as np
matrix = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])
print(matrix[2,0])
    

50


In [39]:
#CHALLENGING PROBLEM
import numpy as np
cube = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(cube[0,0,0])  
print(cube[0,1,1])
print(cube[1,0,0])
print(cube[1,1,1])

1
4
5
8


In [ ]:
#SLICING CONCEPT

#1-D ARRAY
#[10, 20, 30, 40, 50, 60]
#print(numbers[1:4]) = it will start printing from index 1 and will go till index 3
#print(numbers[:3]) = [10 20 30]
#print(numbers[3:]) = [40 50 60]
#print(numbers[:]) = [10 20 30 40 50 60]
#print(numbers[::2]) = [10 30 50]

#2-D ARRAY
#[10, 20, 30],
#[40, 50, 60],
#[70, 80, 90]
#print for entire column print(matrix[:, 1]) = [20 50 80]
#print(matrix[0:2, 1:3]) = [[20 30]
                          # [50 60]]






In [45]:
#SLICING array[start:stop:step]
import numpy as np
number = np.array([10, 20, 30, 40, 50, 60])
print(number[0:3])
print(number[3:])

[10 20 30]
[40 50 60]


In [5]:
#print every second element
import numpy as np
number = np.array([10, 20, 30, 40, 50, 60])
print(number[1::2])

[20 40 60]


In [21]:
#in 2-D array [row_slice, column_slice]
import numpy as np
matrix = np.array([
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]
])
#print first two rows
print(matrix[:2])
#print all rows, but only the second column
print(matrix[0:3,1])

[[1 2 3]
 [4 5 6]]
[2 5 8]


In [24]:
#CHALLENGING PROBLEM
import numpy as np
matrix = np.array([
    [11, 12, 13, 14],
    [21, 22, 23, 24],
    [31, 32, 33, 34],
    [41, 42, 43, 44]
])
print(matrix[1:3, 1:3])
      
    

[[22 23]
 [32 33]]


In [26]:
#RESHAPING
import numpy as np
number = np.array([1,2,3,4,5,6])
matrix = number.reshape(2,3)
print(matrix)


[[1 2 3]
 [4 5 6]]


In [27]:
import numpy as np
number = np.array([1,2,3,4,5,6])
matrix = number.reshape(3,2)
print(matrix)


[[1 2]
 [3 4]
 [5 6]]


In [28]:
import numpy as np
numbers = np.array([10, 20, 30, 40, 50, 60])
matrix =  numbers.reshape(2, -1)
print(matrix)
print(matrix.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [29]:
#CHALLENGING PROBLEM
import numpy as np
numbers = np.arange(1, 13)
print(numbers)
matrix = numbers.reshape(3,4)
print(matrix)
print(matrix.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [30]:
#MATHEMATICAL OPERATION
import numpy as np
a = np.array([5, 10, 15])

b = np.array([2, 4, 6])
print(a + b)


[ 7 14 21]


In [37]:
import numpy as np
a = np.array([5, 10, 15])

b = np.array([2, 4, 6])
print(a - b)
print(a * b)

[3 6 9]
[10 40 90]


In [38]:
import numpy as np
numbers = np.array([10, 20, 30, 40])
print(numbers + 10)
print( numbers / 10)
print(numbers ** 2)

[20 30 40 50]
[1. 2. 3. 4.]
[ 100  400  900 1600]


In [39]:
#CHALLENGING PROBLEM
import numpy as np
marks = np.array([45, 60, 75, 90])
print(marks + 5)
result = (marks + 5) * 2
print(result / 5)



[50 65 80 95]
[20. 26. 32. 38.]


In [42]:
#BROADCASTING
import numpy as np
numbers = np.array([10, 20, 30])
print(numbers + 5)


[15 25 35]


In [43]:
import numpy as np
matrix = np.array([
    [1, 2],
    [3, 4]
])
print(matrix * 10)

[[10 20]
 [30 40]]


In [48]:
import numpy as np
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

bonus = np.array([1, 2, 3])
print(matrix + bonus)


[[11 22 33]
 [41 52 63]]


In [50]:
#CHALLENGING QUESTION
import numpy as np
matrix = np.array([
    [70, 80, 90],
    [60, 75, 85]
])
bonus = np.array([5, 10, 15])
print((matrix + bonus) * 2)

    


[[150 180 210]
 [130 170 200]]


In [53]:
#MEAN,SUM,MAX,MIN
import numpy as np
numbers = np.array([5, 10, 15, 20])

print("sum:", numbers.sum())
print("mean:" ,numbers.mean())


sum: 50
mean: 12.5


In [54]:
import numpy as np
marks = np.array([72, 85, 91, 67, 88])
print("max:", marks.max())
print("min:" , marks.min())

max: 91
min: 67


In [55]:
import numpy as np
prices = np.array([100, 250, 175, 300])
print("sum: " , prices.sum())
print("mean: " ,prices. mean())
print("max: " , prices.max())
print("min: " , prices.min())

sum:  825
mean:  206.25
max:  300
min:  100


In [56]:
#CHALLENGING PROBLEM
import numpy as np
temperatures = np.array([30, 32, 29, 35, 31, 33])
print("sum: " ,  temperatures.sum())
print("mean: " , temperatures.mean())
print("max: " ,  temperatures.max())
print("min: " ,  temperatures.min())

sum:  190
mean:  31.666666666666668
max:  35
min:  29


In [57]:
#AXIS
import numpy as np

matrix = np.array([
    [1, 2],
    [3, 4]
])
print(matrix.sum())
print(matrix.sum(axis = 0))
print(matrix.sum(axis = 1))

10
[4 6]
[3 7]


In [59]:
import numpy as np 
marks = np.array([
    [80, 90],
    [70, 60]
])
print(marks.mean(axis = 0))
print(marks.mean(axis = 1))

[75. 75.]
[85. 65.]


In [61]:
import numpy as np
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])
print(data.max(axis = 0))
print(data.min(axis = 1))

[40 50 60]
[10 40]


In [63]:
#CHALLENGING PROBLEM
import numpy as np
sales = np.array([         #AXIS = 0 FOR COLUMN
                           #AXIS = 1 FOR ROWS
    [100, 150, 200],
    [120, 180, 220],
    [140, 160, 210]
])
print(sales.sum(axis = 0))
print(sales.sum(axis = 1))
print(sales.mean(axis = 0))


[360 490 630]
[450 520 510]
[120.         163.33333333 210.        ]


In [64]:
#RANDOM MODULE
#np.random.rand(5) = 5 random decimal numbers b/w 0 and 1
#np.random.rand(2,3) = 2 x 3 matrix of random decimal numbers
#np.random.randint(1,10,size=5) = 5 random integers from 1 to 9
#np.random.seed(42) = make random results reproducible

In [65]:
import numpy as np
numbers = np.random.rand(6)
print(numbers)

[0.65937168 0.8933931  0.9976514  0.20641874 0.12977587 0.25201332]


In [69]:
import numpy as np
numbers = np.random.rand(3 , 2)
print(numbers)

[[1.42866818e-01 6.50888473e-01]
 [5.64115790e-02 7.21998772e-01]
 [9.38552709e-01 7.78765841e-04]]


In [67]:
import numpy as np
numbers = np.random.randint(10, 50,  size = 8)
print(numbers)

[41 10 23 34 38 37 33 10]


In [68]:
#CHALLENGING PROBLEM
import numpy as np
np.random.seed(42)
matrix = np.random.randint(1, 20,  size = (3, 3))

print("matrix: ", matrix)

print("max : ", np.max(matrix))
print("min: ",  np.min(matrix))
print("mean: ", np.mean(matrix))


matrix:  [[ 7 15 11]
 [ 8  7 19]
 [11 11  4]]
max :  19
min:  4
mean:  10.333333333333334
